### ISSUE TITLE
Support internal locations

### ISSUE THREAD

**Issue by jarshwah** [jfryman/puppet-nginx#340]
To use sendfile (http://wiki.nginx.org/X-accel) one has to have a location that looks like:

```
  location /protected {
    internal;
    alias /path/to/protected/files;
  }
```

The problem is that I can't find a way to set the "internal" directive. I tried:

```yaml
  vhost_protected:
    location: '/protected'
    location_alias: '/path/to/protected/files'
    vhost: 'vhost'
    location_cfg_prepend:
      internal: ''
```

But I believe the empty value for internal means it's just not getting rendered in the template. Am I doing something wrong, or is having empty values an oversight?
