### ISSUE TITLE
location_custom_cfg not processing in template

### ISSUE THREAD

**Issue by VolJin** [jfryman/puppet-nginx#567]
location_custom_cfg not processing in template

**Comment by Zophar78** [comment]
Do you have an example of how you are using it?

**Comment by VolJin** [comment]
I use module nginx from hiera:
nginx::nginx_vhosts:
  "00-default_nonssl":
    www_root: '/var/www/default'
    listen_options: 'default'
    server_name:
      - "%{::fqdn}"
      - "default"
    proxy: 'http://nginx-upstr$uri?$args'
    proxy_set_header:
      - "Host            $host"
      - 'X-Real-IP       $remote_addr'
      - 'X-Forwarded-For $remote_addr'
    location_custom_cfg:
      proxy_ignore_client_abort: 'on'
I think option "proxy_ignore_client_abort" is must be add to default location '/', but isn't add.
in module nginx::resource::vhost this option exist, it exist in ::nginx::resource::location {"${name_sanitized}-default"
But not exist in template in location 'nginx/vhost/locations/proxy.erb'

**Comment by 3flex** [comment]
I'm assuming that should have been formatted like this:

```yaml
nginx::nginx_vhosts:
  "00-default_nonssl":
    www_root: '/var/www/default'
    listen_options: 'default'
    server_name:
      - "%{::fqdn}"
      - "default"
    proxy: 'http://nginx-upstr$uri?$args'
    proxy_set_header:
      - "Host $host"
      - 'X-Real-IP $remote_addr'
      - 'X-Forwarded-For $remote_addr'
    location_custom_cfg:
      proxy_ignore_client_abort: 'on'
```

You're right that `location_custom_cfg` doesn't exist in `vhost/locations/proxy.erb`. Instead, use `location_cfg_prepend` or `location_cfg_append`. That will add it to the beginning or end of the location block.
