### ISSUE TITLE
How to set document root in server block using hiera?

### ISSUE THREAD

**Issue by WallaceTan** [jfryman/puppet-nginx#576]
Current hiera file:
```
nginx::nginx_vhosts:
  "annual-review.local":
    listen_ip: "192.168.33.12"
    www_root: "/var/www/annual-review.local/public"
    try_files:
      - "$uri"
      - "$uri/"
      - "/index.php?$args"
```
Produces nginx hosts config file:
```
server {
  listen                192.168.33.12:80;
  server_name           annual-review.local;

  index  index.html index.htm index.php;

  access_log            /var/log/nginx/annual-review.local.access.log combined;
  error_log             /var/log/nginx/annual-review.local.error.log;

  location / {
    root      /var/www/annual-review.local/public;   # <-- document root in location block
    try_files $uri $uri/ /index.php?$args;
  }
}
```
I have tried different yaml configurations and still unable to set document root in the server block:
```
server {
  listen                192.168.33.12:80;
  server_name           annual-review.local;
  root      /var/www/annual-review.local/public;  # <-- Desired document root in server block

  index  index.html index.htm index.php;

  access_log            /var/log/nginx/annual-review.local.access.log combined;
  error_log             /var/log/nginx/annual-review.local.error.log;

  location / {
    root      /var/www/annual-review.local/public;
    try_files $uri $uri/ /index.php?$args;
  }
}
```

**Comment by WallaceTan** [comment]
Solution:
```
nginx::nginx_vhosts:
  "annual-review.local":
    listen_ip: "192.168.33.12"
    use_default_location: false    # <-- Set document root in server block
    www_root: "/var/www/annual-review.local/public"    # <-- Require www_root to set root in server block
    try_files:
      - "$uri"
      - "$uri/"
      - "/index.php?$args"
```
File output:
```
server {
  listen                192.168.33.12:80;
  server_name           annual-review.local;

  root /var/www/annual-review.local/public;   # <-- Desired document root in server block
  index  index.html index.htm index.php;

  access_log            /var/log/nginx/annual-review.local.access.log combined;
  error_log             /var/log/nginx/annual-review.local.error.log;
}
```
