### ISSUE TITLE
"You cannot collect exported resources without storeconfigs being set" at manifests/resource/upstream.pp:89:5

### ISSUE THREAD

**Issue by herzmut** [jfryman/puppet-nginx#720]
Hello.

When I start my puppet script to create a virtual machine, I get the error message above. I feed your module with the following configuration:
```yaml
upstreams:
        nxv_394dk0458afs:
            name: django
            upstream_fail_timeout: 10s
            members:
                - '127.0.0.1:8000'
```
Yes, the YAML syntax derived from a generated template of PuPHPet (https://puphpet.com). I still think the configuration is valid as the other modules in your project work perfectly. The error messages mentions location.pp explicitly.

This error does not keep me from creating my machine and makes this a low-priority issue.
