### ISSUE TITLE
add_header for location

### ISSUE THREAD

**Issue by apazga** [jfryman/puppet-nginx#729]
Hi,

There is no possibility to use add_header inside a location, right? I tried e.g. the following from hiera:
```yaml
nginx::nginx_locations:
  'myhostname-alias':
    location: '^~ /wp-content'
    vhost: 'myhostname'
    location_alias: '/var/www/myhostname/wp-content'
    add_header:
      'Access-Control-Allow-Origin': '*'
```

But it gives the following error:
```
Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Nginx::Resource::Location[myhostname-alias]: has no parameter named 'add_header' on node myhostname.mydomain.com
```

Do you know any other possibility to do this? Or is not supported by now?
Thanks in advance

**Comment by tux-o-matic** [comment]
@apazga place it under 'location_cfg_append' which expects a hash of custom parameters.
So your example:
```yaml
nginx::nginx_locations:
  'myhostname-alias':
    location: '^~ /wp-content'
    vhost: 'myhostname'
    location_alias: '/var/www/myhostname/wp-content'
    location_cfg_append:
      add_header: 'Access-Control-Allow-Origin *'
```
