### ISSUE TITLE
How to use Hiera?

### ISSUE THREAD

**Issue by davividal** [jfryman/puppet-nginx#836]
I'm writing a custom module to get jenkins up and running. Jenkins is fine, but I'm trying to setup nginx using hiera.
Here is my `data/common.yaml`:

```yaml
---
nginx::nginx_upstreams:
  'jenkins':
    ensure: present
    members:
      - localhost:9000
nginx::nginx_vhosts:
  'jenkins.local':
    ssl: true
    proxy: 'http://jenkins'
```

My `metadata.json`:
```json
{
  "author": "Davi Koscianski Vidal",
  "dependencies": [
    {"name":"jfryman/nginx", "version_requirement":">=0.3.0 < 1.0.0"}
  ],
  "license": "",
  "name": "davividal-jenkins",
  "operatingsystem_support": [],
  "project_page": "",
  "requirements": [],
  "source": "",
  "summary": "",
  "tags": [],
  "version": "0.1.0",
  "data_provider": "hiera"
}
```

Should I put anything other than `class { 'nginx': }` on my init.pp?
